DROP TABLE IF EXISTS attendance_logs;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS admins;

-- Tabel Peserta
CREATE TABLE peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nim VARCHAR(20) UNIQUE NOT NULL,
    nama VARCHAR(255) NOT NULL,
    prodi VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabel Pengaturan (Untuk sesi absensi)
CREATE TABLE pengaturan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    max_absen INT DEFAULT 1,
    sesi_aktif BOOLEAN DEFAULT TRUE
);

-- Tabel Absensi
CREATE TABLE absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peserta_id BIGINT REFERENCES peserta(id) ON DELETE CASCADE,
    waktu_absen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    status VARCHAR(50) DEFAULT 'Hadir' -- Hadir, Terlambat, Manual
);
